# 1)
usersNumber = int(input("enter random number: "))
UsersNumber = int(input("enter random number: "))
users_number = int(input("enter random number: "))
print(usersNumber + 5)
print(UsersNumber * 5)
print(users_number ** 5)
print(usersNumber // 5)
print(usersNumber - 5)

# 2)
user_name = input("enter your name: ")
lastName = input("enter your last name: ")
print("your", "name", "is", user_name, lastName)